# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:

  build_and_publish:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      
      - name: Print PWD
        run: pwd
        
      - name: Native compile
        run: |
          cd SwingTestTwo/
          ./gradlew nativeCompile
        
      - name: Create artifact
        run: |
          cd SwingTestTwo/
          mkdir macos-latest-release
          cp build/native/nativeCompile/SwingTestTwo macos-latest-release/
          
      - name: ZIP artifact
        run: |
          cd SwingTestTwo/
          zip -r macos-latest.zip macos-latest-release/
          mv macos-latest.zip ..
          
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: macos-latest
          path: macos-latest.zip

#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
