# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:

  build_and_publish:

    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v3

      - name: Get into project
        run: cd ${{github.workspace}}
        
      - name: List project directory
        run: ls -R

#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
